name:                nhanse-scraper
version:             0.1.0.0
github:              "githubuser/nhanse-scraper"
license:             BSD3
author:              "Levi Butcher"
maintainer:          "levibutcher355@gmail.com"
copyright:           "2022 Levi Butcher"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/levibutcher/nhanse-scraper#readme>

dependencies:
- base >=4.4 && < 5
- scalpel
- parsec
- transformers
- cassava
- bytestring
- http-client

library:
  source-dirs: src

executables:
  nhanse-scraper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nhanse-scraper

tests:
  nhanse-scraper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nhanse-scraper
